resctucted redux with re-ducks approach.
ekostandov/react-shop pull request #31
Opened 2022-06-01 14:00 UTC by ekostandov

2022-06-02 15:55 UTC, sihorjs requested changes
LGTM but we have some codestyle issues

2022-06-02 15:55 UTC, singvarr commented on src/store/cart.js
> +const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
Add a rule that requires a new line between `import` and other statemenet

2022-06-02 15:55 UTC, singvarr commented on src/store/cart.js
> +        [action.id]: (state[action.id] || 0) + action.count,
1. Simplify it. Create a ternany that will check presence of a product in the cart and if it exists increment quantity; otherwise add new product to cart 
2. Do we need `action.count`? I assume that it should increase quantity by 1 always.

2022-06-02 15:55 UTC, singvarr commented on src/store/cart.js
> +    case SET_PRODUCT_QUANTITY_IN_CART: {
let's rename to `UPDATE_PRODUCT_QUANTITY`

2022-06-02 15:55 UTC, sihorjs commented on src/store/like.js
>  const productsLikesReducer = (state = {}, action) => {
Just `likeReducer`

2022-06-02 15:55 UTC, singvarr commented on src/store/like.js
> +const LIKE = 'LIKE';
`LIKE_PRODUCT` and `DISLIKE_PRODUCT`

2022-06-02 15:55 UTC, singvarr commented on src/Features/Cart/CartProductListItemExtended.js
> +  removePRoductFromCart,
check import please

2022-06-02 15:55 UTC, singvarr commented on src/Features/Cart/CartProductListItemExtended.js
> +    { addProductToCart, setProductQuantityInCart, removePRoductFromCart },
`addProductToCart` should be validated

2022-06-03 08:48 UTC, ekostandov commented on src/store/cart.js
> +        [action.id]: (state[action.id] || 0) + action.count,
1. I'm not sure I understand how to implement it.
2. It adds to cart the choosen quantity in `product-quantity` input.

2022-06-07 10:10 UTC, sihorjs requested changes

2022-06-07 10:10 UTC, sihorjs commented on src/store/cart.js
> +        [action.id]: (state[action.id] || 0) + action.count,
In this case rename action type to `SET_PRODUCT_QUANTITY` and update name of action creator

2022-08-15 19:39 UTC, sihorjs reviewed
LGTM

2022-08-15 19:39 UTC, sihorjs commented on src/Features/Cart/CartProductListItem.js
> +// CartProductListItem.defaultProps = {
Don't forget to remove commented code

2022-08-15 19:48 UTC, ekostandov commented on src/Features/Cart/CartProductListItem.js
> +// CartProductListItem.defaultProps = {
Removed commented code.

2022-08-15 20:07 UTC, merged